# Generated by Django 6.0.6 on 2026-06-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('auto', 'Автомат'), ('manual', 'Механика'), ('PDK', 'Робот (PDK)')], max_length=10),
        ),
    ]
